<a href="https://colab.research.google.com/github/lqiang79/data_science_learning/blob/master/numpy_start.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from io import BytesIO
import pandas as pd
import matplotlib.pyplot as plt
% matplotlib inline

In [0]:
data = "1, 2, 3\n4, 5, 6"
np.genfromtxt(BytesIO(data.encode('utf-8')), delimiter=",")

array([[1., 2., 3.],
       [4., 5., 6.]])

In [0]:
np.genfromtxt(BytesIO(data.encode('utf-8')), delimiter=",", usecols=(0, -1), dtype="int")

array([[1, 3],
       [4, 6]])

In [0]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [0]:
# select 0 to 8, with step of 2
a[:8:2]

array([  0,   8,  64, 216])

In [0]:
a = np.floor(10*np.random.random((3,4)))
a

array([[7., 9., 9., 5.],
       [2., 6., 1., 4.],
       [0., 5., 3., 3.]])

In [0]:
a.shape #显示形状，相应的几纬

(3, 4)

In [0]:
a.reshape(6, 2) # 改变矩阵的形状

array([[7., 9.],
       [9., 5.],
       [2., 6.],
       [1., 4.],
       [0., 5.],
       [3., 3.]])

In [0]:
a.ravel() # change the multi axis to 1

array([7., 9., 9., 5., 2., 6., 1., 4., 0., 5., 3., 3.])

In [0]:
a.T

array([[7., 2., 0.],
       [9., 6., 5.],
       [9., 1., 3.],
       [5., 4., 3.]])

In [0]:
a.shape

(3, 4)

In [0]:
a.T.shape

(4, 3)

In [0]:
a.resize(2,6)

In [0]:
a

array([[7., 9., 9., 5., 2., 6.],
       [1., 4., 0., 5., 3., 3.]])